name: GAWF Name
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run:
          echo "Hello World !!!"
          echo "on second line"
      - name: Print Goodbye
        run: echo "Don - Bye !!!"
  second-job:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses:	actions/checkout@v3.5.3
      - name: Second Job Second Step
        run: echo "2" 	
