name: GAWF Name
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run:
          echo "Hello World !!!"
          echo "on second line"
      - name: Print Goodbye
        run: echo "Don - Bye !!!"
  second-job:
    runs-on: windows-latest
    steps:
      - name: Second Job First step
        run:	echo "1"
      - name: Second Job Second Step
        run: echo "2" 	
