name: GAWF Name
on: 
  push:
    paths:
      - '.github/workflows/*'
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World !!!"
          echo "on second line"
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
      - name: Print Goodbye
        run: echo "Job 1 Done !!!"
  second-job:
    needs: first-job
    runs-on: windows-latest
    steps:
    # - name: Get Code
    #   uses:	actions/checkout@v3.5.3
    #  - name: Install NodeJS
    #    uses: actions/setup-node@v3
    #   with:
    #     node-version: 18
      - name: Second Job Second Step
        run: echo "End of Job 2 - Bye " 	
